spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todolist
    username: root
    password: lkjhg09876

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

    show-sql: true

page-size: 10
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE